### ISSUE TITLE
Remove local socket library. 

### ISSUE THREAD

**Issue by nawazdhandala** [CloudBoost/JavaScriptSDK#24]

**Comment by telvin** [comment]
On NodeJs, when listening the event on this line

> CB.CloudObject.on('TABLE_NAME', ...)

it throws error about localstorage is not defined. My workaround is install ng-localstorage (which is not described on your doc), and move two lines below to the top

> ....
> if (CB._isNode) {
>     var LocalStorage = require('node-localstorage').LocalStorage;
>     var localStorage = new LocalStorage('./scratch');
> }
> 
> /*
>  Parse codes:
>  */
> CB._ajaxIE8 = function(method, url, data) { ....
>

**Comment by shubhamqweasd** [comment]
@telvin , we are currently refactoring the entire sdk , can you please try using the new sdk you will find in the es6 branch of this repo.

**Comment by telvin** [comment]
@shubhamqweasd  Is it available yet? I could see there's only single master branch.

**Comment by nawazdhandala** [comment]
We merged es6 to master. You can use master directly. :)

**Comment by telvin** [comment]
I have checked it out and It does not work. The error is still there

ReferenceError: localStorage is not defined.

I must insist that this issue happens on NodeJS

**Comment by nawazdhandala** [comment]
@shubhamqweasd Can you please check this out. :)

**Comment by shubhamqweasd** [comment]
@telvin , can you please re-install cloudboost from npm i.e `npm i cloudboost`, that might fix the localStorage dependency issue, or you can just install localStorage `npm install localStorage` to resolve that particular dependency.

**Comment by telvin** [comment]
I have removed the node_modules folder and reinstall everything again, but it does not get fixed.
My dependencies is simply as below:

> "dependencies": {
>     "cloudboost": "^1.2.1",
>     "localStorage": "^1.0.3"
>   }

**Comment by shubhamqweasd** [comment]
@telvin localStorage error comes during server boot up or just when you use this `CB.CloudObject.on('TABLE_NAME', ...)` ? also which version of node are you using ?

**Comment by shubhamqweasd** [comment]
@telvin , also please console this and tell me the result , ` console.log(CB._isNode) `

**Comment by telvin** [comment]
@shubhamqweasd The output is 

> true

.

**Comment by shubhamqweasd** [comment]
@telvin please check now

**Comment by telvin** [comment]
@shubhamqweasd Eventually, the error is gone. Thank you for taking your time to address this issue.
